services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: template-frontend
    working_dir: /usr/src/app
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules  # Not synchronizing the local node_modules folder with the container
    environment:
      NODE_ENV: development  # Setting environment variables
    command: pnpm run dev
